fix(homelab): remove reference to non-existent virtual-service.yaml in minio-loki
Remove virtual-service.yaml from minio-loki kustomization resources as the file
does not exist in the directory. This was causing validation workflow to fail.

Error: accumulating resources from 'virtual-service.yaml': no such file or directory